// clients/sveltekit-client/src/lib/components/form/TextInput/TextInput.svelte
<script lang="ts">
	// Styling
	import './TextInput.scss';

	// Props
	export let label: string;
	export let subLabel: string = '';
	export let required = false;
	export let value: string = '';
	export let type: 'password' | 'text' = 'text';
	export let customClass: string = '';
</script>

<div class="text-input-container {customClass}">
	<label for={label.replace(' ', '-')}>
		{label}
		{#if subLabel !== ''}
			<span>{subLabel}</span>
		{/if}
	</label>
	<input name={label.replace(' ', '-')} {required} {...{ type }} bind:value />
</div>

// clients/react-client/src/components/form/TextInput/TextInput.tsx
// Styling
import "./TextInput.scss";

interface IProps {
  label: string;
  subLabel?: string;
  type?: "password" | "text";
  customClass?: string;
  value: string;
  onChange: Function;
  required?: boolean;
}

export default function TextInput({
  label,
  subLabel = "",
  type = "text",
  value,
  onChange,
  customClass = "",
  required = false,
}: IProps) {
  return (
    <div className={"text-input-container " + customClass}>
      <label htmlFor={label.replace(" ", "-")}>
        {label}
        {subLabel !== "" && <span>{subLabel}</span>}
      </label>
      <input
        required={required}
        name={label.replace(" ", "-")}
        type={type}
        value={value}
        onChange={(e) => onChange(e.target.value)}
      />
    </div>
  );
}
