// clients/react-client/src/components/chat/SidebarActions/SidebarActions.tsx
// Package imports
import { FontAwesomeIcon } from "@fortawesome/react-fontawesome";
import { faGear, faPlus } from "@fortawesome/free-solid-svg-icons";
import { Dispatch, SetStateAction, useState } from "react";

// Custom imports
import NewChatMenu from "../NewChatMenu/NewChatMenu";

// Styling
import "./SidebarActions.scss";

interface IProps {
  setSearchTerm: Dispatch<SetStateAction<string>>;
}

export default function SidebarActions({ setSearchTerm }: IProps) {
  // Open states of menus
  const [settingsMenu, setSettingsMenu] = useState(false);
  const [newChatMenu, setNewChatMenu] = useState(false);

  // Close the menus if click on background
  const closeMenu = (e: any) => {
    if (e.target.classList.contains("sidebar-actions-menu-bg")) {
      setSettingsMenu(false);
      setNewChatMenu(false);
    }
  };

  return (
    <div className="sidebar-actions-container">
      <input
        type="text"
        placeholder="Suche"
        onChange={(e) => setSearchTerm(e.target.value)}
      />
      <button className="action" onClick={() => setNewChatMenu(true)}>
        <FontAwesomeIcon icon={faPlus} />
      </button>
      <button className="action" onClick={() => setSettingsMenu(true)}>
        <FontAwesomeIcon icon={faGear} />
      </button>
      {(settingsMenu || newChatMenu) && (
        <div className="sidebar-actions-menu-bg" onClick={closeMenu}>
          {settingsMenu && <div></div>}
          {newChatMenu && <NewChatMenu close={() => setNewChatMenu(false)} />}
        </div>
      )}
    </div>
  );
}

// clients/sveltekit-client/src/lib/components/chat/SidebarActions/SidebarActions.svelte
<script lang="ts">
	// Styling
	import './SidebarActions.scss';

	// Components
	import { FontAwesomeIcon } from '@fortawesome/svelte-fontawesome';
	import { faGear, faPlus } from '@fortawesome/free-solid-svg-icons';
	import NewChatMenu from '../NewChatMenu/NewChatMenu.svelte';

	// Props
	export let searchTerm: string;

	// States
	let newChatMenu = false;
	let settingsMenu = false;

	/**
	 * Close all menus
	 */
	function closeMenu() {
		newChatMenu = false;
		settingsMenu = false;
	}
</script>

<div class="sidebar-actions-container">
	<input type="text" placeholder="Suche" bind:value={searchTerm} />
	<button class="action" on:click={() => (newChatMenu = true)}>
		<FontAwesomeIcon icon={faPlus} />
	</button>
	<button class="action" on:click={() => (settingsMenu = true)}>
		<FontAwesomeIcon icon={faGear} />
	</button>
	{#if settingsMenu || newChatMenu}
		<div class="sidebar-actions-menu-bg" on:click={closeMenu}>
			{#if settingsMenu}<div></div>{/if}
			{#if newChatMenu}<NewChatMenu close={closeMenu} />{/if}
		</div>
	{/if}
</div>
