// clients/sveltekit-client/src/lib/components/form/SubmitButtonInput/SubmitButtonInput.svelte
<script lang="ts">
	// Styling
	import './SubmitButtonInput.scss';

	// Props
	export let type: 'primary' | 'secondary' = 'primary';
	export let label: string;
	export let loading: boolean = false;
</script>

<button type="submit" class="submit-button-input {type}" disabled={loading}>
	{#if loading}
		<div class="loading-circle"></div>
	{:else}
		{label}
	{/if}
</button>

// clients/react-client/src/components/form/SubmitButtonInput/SubmitButtonInput.tsx
// Styling
import "./SubmitButtonInput.scss";

interface IProps {
  type: "primary" | "secondary";
  label: string;
  loading?: boolean;
}

export default function SubmitButtonInput({
  type,
  label,
  loading = false,
}: IProps) {
  return (
    <button
      type="submit"
      className={`submit-button-input ${type}`}
      disabled={loading}
    >
      {loading ? <div className="loading-circle"></div> : label}
    </button>
  );
}
