// clients/sveltekit-client/src/lib/components/form/CheckboxInput/CheckboxInput.svelte
<script lang="ts">
	// Styling
	import './CheckboxInput.scss';

	// Props
	export let label: string;
	export let value: boolean = false;
</script>

<div class="checkbox-input-container" on:click={() => (value = !value)}>
	<label for={label.replace(' ', '-')}>{label}</label>
	<input type="checkbox" name={label.replace(' ', '-')} on:click={() => (value = !value)} />
	<div class={'checkbox ' + (value && 'checked')}>
		{#if value}
			<div class="checked-marker"></div>
		{/if}
	</div>
</div>

// clients/react-client/src/components/form/CheckboxInput/CheckboxInput.tsx
// Styling
import "./CheckboxInput.scss";

interface IProps {
  label: string;
  value: boolean;
  onChange: Function;
}

export default function CheckboxInput({ label, value, onChange }: IProps) {
  return (
    <div className="checkbox-input-container" onClick={() => onChange(!value)}>
      <label htmlFor={label.replace(" ", "-")}>{label}</label>
      <input
        type="checkbox"
        name={label.replace(" ", "-")}
        onClick={() => onChange(!value)}
      />
      <div className={"checkbox " + (value && "checked")}>
        {value && <div className="checked-marker"></div>}
      </div>
    </div>
  );
}
