// clients/sveltekit-client/src/lib/components/chat/ChatDetailsMenu/ChatDetailsMenu.svelte
<script lang="ts">
	import { users } from '$lib/stores/UserStore';
	import type { Chat, User } from '$lib/types/prisma';
	import Avatar from '../Avatar/Avatar.svelte';
	import './ChatDetailsMenu.scss';
	import GroupAvatarContainer from './GroupAvatarContainer.svelte';
	import GroupTitleContainer from './GroupTitleContainer.svelte';

	export let chat: Chat;
	export let close: () => void;
	let userList: User[] = [];

	/**
	 * Creates a readable string from date object
	 * @param date
	 * @param format
	 * @returns
	 */
	const getReadableDate = (date = new Date(), format = 'hh:MM') => {
		const dateObj = new Date(date);

		if (
			dateObj.getDay() !== new Date().getDay() ||
			dateObj.getMonth() !== new Date().getMonth() ||
			dateObj.getFullYear() !== new Date().getFullYear()
		) {
			return new Date(date).format('dd.mm.yyyy um hh:MM');
		}
		return new Date(date).format(format);
	};

	// Close the menu on background click
	const closeMenu = (e: any) => {
		if (e.target.classList.contains('chat-details-menu-bg')) {
			close();
		}
	};

	users.subscribe((users) => (userList = users));
</script>

<div class="chat-details-menu-bg" on:click={closeMenu}>
	<div class="chat-details-menu-container">
		<GroupAvatarContainer chatId={chat.id} src={chat.avatar || 'clzmp4jk80000nudqn6vmauc4.jpg'} />
		<div class="title-container">
			<GroupTitleContainer chatId={chat.id} name={chat.name || ''} memberCount={chat.ChatParticipant.length} />
		</div>
		<ul class="members">
			{#each chat.ChatParticipant as cp (cp.id)}
				<li>
					<Avatar img={userList.find((u) => u.id === cp.User.id)?.avatar} userId={cp.User.id} />
					<div class="basic-information">
						<span class="username">
							<span>{cp.User.username}</span>
							{#if cp.creator}
								<span class="creator">Inhaber</span>
							{/if}
						</span>
						<span class="online">
							{#if userList.find((u) => u.id === cp.User.id)?.online}
								Online
							{:else if userList.find((u) => u.id === cp.User.id)?.lastSeen}
								{#each userList as user}
									{#if user.id === cp.User.id && user.lastSeen}
										zul. online: {getReadableDate(user.lastSeen)}
									{/if}
								{/each}
							{:else}
								zul. online: Nie
							{/if}
						</span>
					</div>
					<div class="actions"></div>
				</li>
			{/each}
		</ul>
	</div>
</div>

// clients/react-client/src/components/chat/ChatDetailsMenu/ChatDetailsMenu.tsx
import { useContext, useState } from "react";
import { Chat } from "../../../types/prisma";
import "./ChatDetailsMenu.scss";
import { UserOnlineContext } from "../../../context/UserOnlineContext";
import Avatar from "../Avatar/Avatar";
import { FontAwesomeIcon } from "@fortawesome/react-fontawesome";
import {
  faFloppyDisk,
  faImage,
  faPencil,
  faXmark,
} from "@fortawesome/free-solid-svg-icons";
import socket from "../../../service/socket.service";
import { ChatsContext } from "../../../context/ChatsContext";
import { useMutation } from "@tanstack/react-query";
import ApiService from "../../../service/api.service";

/**
 * Creates a readable string from date object
 * @param date
 * @param format
 * @returns
 */
const getReadableDate = (date = new Date(), format = "hh:MM") => {
  const dateObj = new Date(date);

  if (
    dateObj.getDay() !== new Date().getDay() ||
    dateObj.getMonth() !== new Date().getMonth() ||
    dateObj.getFullYear() !== new Date().getFullYear()
  ) {
    return new Date(date).format("dd.mm.yyyy um hh:MM");
  }
  return new Date(date).format(format);
};

interface IProps {
  chat: Chat;
  close: () => void;
}

export default function ChatDetailsMenu({ chat, close }: IProps) {
  const userList = useContext(UserOnlineContext);

  // Close the menu on background click
  const closeMenu = (e: any) => {
    if (e.target.classList.contains("chat-details-menu-bg")) {
      close();
    }
  };

  return (
    <div className="chat-details-menu-bg" onClick={closeMenu}>
      <div className="chat-details-menu-container">
        <GroupAvatarContainer
          chatId={chat.id}
          src={chat.avatar || "clzmp4jk80000nudqn6vmauc4.jpg"}
        />
        <div className="title-container">
          <GroupTitleContainer
            chatId={chat.id}
            name={chat.name || ""}
            memberCount={chat.ChatParticipant.length}
          />
        </div>
        <ul className="members">
          {chat.ChatParticipant.map((cp) => {
            const user = userList.getUserMeta(cp.User.id);

            return (
              <li>
                <Avatar img={user?.avatar} userId={user?.id} />
                <div className="basic-information">
                  <span className="username">
                    <span>{cp.User.username}</span>
                    {cp.creator && <span className="creator">Inhaber</span>}
                  </span>
                  <span className="online">
                    {user?.online
                      ? "Online"
                      : user?.lastSeen
                        ? "zul. online: " +
                          getReadableDate(new Date(user?.lastSeen))
                        : "zul. online: Nie"}
                  </span>
                </div>
                <div className="actions"></div>
              </li>
            );
          })}
        </ul>
      </div>
    </div>
  );
}

interface IGroupAvatarContainerProps {
  chatId: string;
  src: string;
}

const GroupAvatarContainer = ({ src, chatId }: IGroupAvatarContainerProps) => {
  const { refetch } = useContext(ChatsContext);

  const avatarUpload = useMutation({
    mutationFn: (file: any) => {
      return ApiService.changeGroupAvatar(chatId, file);
    },
    onSuccess: () => {
      refetch();
    },
    onError: (err) => {
      console.log(err);
    },
  });

  const handleFileChange = (e: React.ChangeEvent<HTMLInputElement>) => {
    if (e.target.files) {
      avatarUpload.mutate(e.target.files[0]);
    }
  };

  const triggerFileSelect = () => {
    document.getElementById("file")?.click();
  };

  return (
    <>
      <img src={"http://localhost:4000/avatar/" + src} />
      <input id="file" type="file" onChange={handleFileChange} />
      <button className="change-avatar" onClick={triggerFileSelect}>
        <FontAwesomeIcon icon={faImage} />
      </button>
    </>
  );
};

interface IGroupTitleContainerProps {
  chatId: string;
  name: string;
  memberCount: number;
}

const GroupTitleContainer = ({
  chatId,
  name,
  memberCount,
}: IGroupTitleContainerProps) => {
  const { refetch } = useContext(ChatsContext);
  const [editNameOpen, setEditNameOpen] = useState(false);
  const [value, setValue] = useState(name);

  const save = () => {
    if (value !== "") {
      socket.emit("chat-edit", { chatId, name: value }, () => {
        refetch();
        setEditNameOpen(false);
      });
    }
  };

  if (editNameOpen) {
    return (
      <>
        <span className="name">
          <input
            type="text"
            value={value}
            onChange={(e) => setValue(e.target.value)}
          />
          <button className="edit-name action" onClick={save}>
            <FontAwesomeIcon icon={faFloppyDisk} />
          </button>
          <button
            className="edit-name action"
            onClick={() => {
              setEditNameOpen(false);
              setValue(name);
            }}
          >
            <FontAwesomeIcon icon={faXmark} />
          </button>
        </span>
        <span className="members-counter">{memberCount} Mitglieder</span>
      </>
    );
  }

  return (
    <>
      <span className="name">
        {value}
        <button className="edit-name" onClick={() => setEditNameOpen(true)}>
          <FontAwesomeIcon icon={faPencil} />
        </button>
      </span>
      <span className="members-counter">{memberCount} Mitglieder</span>
    </>
  );
};
