// clients/sveltekit-client/src/lib/components/chat/NewMessageBar/NewMessageBar.svelte
<script lang="ts">
	import './NewMessageBar.scss';
	import { FontAwesomeIcon } from '@fortawesome/svelte-fontawesome';
	import { faPaperPlane } from '@fortawesome/free-solid-svg-icons';
	import { selectedChat } from '$lib/stores/SelectedChatStore';
	import type { Chat } from '$lib/types/prisma';
	import socket from '$lib/services/socket.service';
	import { QueryObserver } from '@tanstack/svelte-query';
	import QueryService from '$lib/services/query.service';

	let content = '';
	let selected: Chat | null = null;

	let observer = new QueryObserver(QueryService.getQueryClient(), { queryKey: ['chats'] });
	selectedChat.subscribe((chat) => (selected = chat));

	const sendMessage = () => {
		if (content !== '' && selected) {
			socket.emit('message-new', { chatId: selected.id, content }, () => {
				// TODO: implement message without refetching
				$observer.refetch();
			});

			// Reset field value
			content = '';
		}
	};
</script>

<div class="new-message-bar-container">
	<div class="input-container">
		<input
			type="textfield"
			bind:value={content}
			on:keydown={(e) => {
				if (e.key === 'Enter') {
					sendMessage();
				}
			}}
		/>
		<button on:click={sendMessage}>
			<FontAwesomeIcon icon={faPaperPlane} />
		</button>
	</div>
</div>

// clients/react-client/src/components/chat/NewMessageBar/NewMessageBar.tsx
import { useContext, useState } from "react";
import "./NewMessageBar.scss";
import { FontAwesomeIcon } from "@fortawesome/react-fontawesome";
import { faPaperPlane } from "@fortawesome/free-solid-svg-icons";
import socket from "../../../service/socket.service";
import { ChatsContext } from "../../../context/ChatsContext";

export default function NewMessageBar() {
  const [content, setContent] = useState("");
  const { selectedChat, refetch } = useContext(ChatsContext);

  const sendMessage = () => {
    if (content !== "") {
      socket.emit("message-new", { chatId: selectedChat.id, content }, () => {
        // TODO: implement message without refetching
        refetch();
      });

      // Reset field value
      setContent("");
    }
  };

  return (
    <div className="new-message-bar-container">
      <div className="input-container">
        <input
          type="textfield"
          value={content}
          onChange={(e) => setContent(e.target.value)}
          onKeyDown={(e) => {
            if (e.key === "Enter") {
              sendMessage();
            }
          }}
        />
        <button onClick={sendMessage}>
          <FontAwesomeIcon icon={faPaperPlane} />
        </button>
      </div>
    </div>
  );
}
