// clients/sveltekit-client/src/lib/components/chat/NewChatMenu/NewChatMenu.svelte
<script lang="ts">
	// Styling
	import './NewChatMenu.scss';

	// Components
	import ButtonInput from '$lib/components/form/ButtonInput/ButtonInput.svelte';
	import MessageBox from '$lib/components/form/MessageBox/MessageBox.svelte';
	import SubmitButtonInput from '$lib/components/form/SubmitButtonInput/SubmitButtonInput.svelte';
	import TextInput from '$lib/components/form/TextInput/TextInput.svelte';

	// Various
	import socket from '$lib/services/socket.service';
	import { QueryObserver } from '@tanstack/svelte-query';
	import QueryService from '$lib/services/query.service';

	// Props
	export let close: () => void;

	// States
	let name = '';
	let username = '';
	let message = '';

	// Register listener to chats query
	let observer = new QueryObserver(QueryService.getQueryClient(), { queryKey: ['chats'] });

	/**
	 * Create new chat via socket connection
	 */
	const newChat = () => {
		socket.emit('chat-new', { name: name, users: [username] }, (d: any) => {
			if (d) {
				message = 'Nutzer konnte nicht gefunden werden.';
			} else {
				$observer.refetch();
				close();
			}
		});
	};
</script>

<div class="new-chat-menu">
	<p>Chat erstellen</p>
	{#if message !== ''}
		<MessageBox type="error" {message} />
	{/if}
	<form on:submit|preventDefault={newChat}>
		<TextInput label="Chat Name" bind:value={name} />
		<TextInput label="Benutzer" bind:value={username} />
		<div class="action-container">
			<ButtonInput type="secondary" label="Abbrechen" onClick={close} />
			<SubmitButtonInput type="primary" label="Chat erstellen" />
		</div>
	</form>
</div>

// clients/react-client/src/components/chat/NewChatMenu/NewChatMenu.tsx
// Package imports
import { FormEvent, useContext, useState } from "react";

// Custom imports
import TextInput from "../../form/TextInput/TextInput";
import SubmitButtonInput from "../../form/SubmitButtonInput/SubmitButtonInput";
import MessageBox from "../../form/MessageBox/MessageBox";
import socket from "../../../service/socket.service";
import { ChatsContext } from "../../../context/ChatsContext";
import ButtonInput from "../../form/ButtonInput/ButtonInput";

// Styling
import "./NewChatMenu.scss";

interface IProps {
  close: () => void;
}

export default function NewChatMenu({ close }: IProps) {
  // Chat context
  const chats = useContext(ChatsContext);

  // Input and message states
  const [name, setName] = useState("");
  const [username, setUsername] = useState("");
  const [message, setMessage] = useState("");

  // Create new chat with socket connection
  const newChat = (e: FormEvent) => {
    e.preventDefault();
    socket.emit("chat-new", { name: name, users: [username] }, (d: any) => {
      if (d) {
        setMessage("Nutzer konnte nicht gefunden werden.");
      } else {
        chats.refetch();
        close();
      }
    });
  };

  return (
    <div className="new-chat-menu">
      <p>Chat erstellen</p>
      {message !== "" && <MessageBox type={"error"} message={message} />}
      <form onSubmit={newChat}>
        <TextInput label="Chat Name" value={name} onChange={setName} />
        <TextInput label="Benutzer" value={username} onChange={setUsername} />
        <div className="action-container">
          <ButtonInput type="secondary" label="Abbrechen" onClick={close} />
          <SubmitButtonInput type="primary" label="Chat erstellen" />
        </div>
      </form>
    </div>
  );
}
