// clients/react-client/src/views/Chat/Chat.tsx
// Package imports
import { useContext, useEffect } from "react";

// Custom imports
import Sidebar from "../../components/chat/Sidebar/Sidebar";
import ChatWindow from "../../components/chat/ChatWindow/ChatWindow";
import Socket from "../../service/socket.service";
import { ChatsContext } from "../../context/ChatsContext";

// Styling
import "./Chat.scss";

function Chat() {
  // Hooks
  const chats = useContext(ChatsContext);

  // Connect socket
  useEffect(() => {
    Socket.connect();

    return () => {
      Socket.disconnect();
    };
  }, []);

  if (chats.isPending) return <></>;

  return (
    <div className="chat-container">
      <Sidebar />
      <ChatWindow />
    </div>
  );
}

export default Chat;

// clients/sveltekit-client/src/routes/chat/+page.svelte
<script lang="ts">
	// Styling
	import './+page.scss';

	// Components
	import Sidebar from '$lib/components/chat/Sidebar/Sidebar.svelte';
	import UserStoreProvider from '$lib/components/general/UserStoreProvider/UserStoreProvider.svelte';
	import ChatStoreProvider from '$lib/components/general/ChatStoreProvider/ChatStoreProvider.svelte';
	import ChatWindow from '$lib/components/chat/ChatWindow/ChatWindow.svelte';
</script>

<div class="chat-container">
	<UserStoreProvider>
		<ChatStoreProvider>
			<Sidebar />
			<ChatWindow />
		</ChatStoreProvider>
	</UserStoreProvider>
</div>
