// clients/react-client/src/components/chat/ChatHeader/ChatHeader.tsx
// Package imports
import { useContext, useState } from "react";

// Custom imports
import TokenService from "../../../service/token.service";
import Avatar from "../Avatar/Avatar";
import { ChatsContext } from "../../../context/ChatsContext";
import { UserOnlineContext } from "../../../context/UserOnlineContext";
import LastSeen from "../LastSeen/LastSeen";

// Styling
import "./ChatHeader.scss";
import ChatDetailsMenu from "../ChatDetailsMenu/ChatDetailsMenu";

export default function ChatHeader() {
  const { selectedChat, isPending } = useContext(ChatsContext);
  const [chatDetailsMenu, setChatDetailsMenu] = useState(false);
  const userList = useContext(UserOnlineContext);
  let self = TokenService.getUser();

  // Show loading UI
  if (isPending)
    return (
      <div
        className="chat-header-container"
        onClick={() => setChatDetailsMenu(true)}
      >
        <div className="user-information">
          <Avatar loading={true} />
          <div className="user-meta">
            <div className="username loading"></div>
            <div className="last-seen loading"></div>
          </div>
        </div>
      </div>
    );

  // Show empty UI if no chat is selected
  if (selectedChat === null) return <></>;

  // Get userlist meta data and remove self
  let users = userList.getUsersMetaByParticipants(selectedChat.ChatParticipant);
  const index = users.findIndex((u) => u.id === self?.id);
  users = users.toSpliced(index, 1);

  // Determine chat type
  const isGroupChat = users.length > 1;
  const isSingleChat = users.length === 0;
  const isNormalChat = users.length === 1;

  let image = "";
  let nameTemp = "";

  // Set variables if groupchat
  if (isGroupChat) {
    image = selectedChat.avatar || "";
    nameTemp = selectedChat.name as string;
  }

  // Set variables if 1:1 chat
  if (isNormalChat) {
    image = users[0].avatar as string;
    nameTemp = users[0].username;
  }

  // Set variables if only one member
  if (isSingleChat) {
    image = self?.avatar || "";
    nameTemp = selectedChat.name as string;
  }

  return (
    <>
      <div
        className="chat-header-container"
        onClick={() => setChatDetailsMenu(true)}
      >
        <div className="user-information">
          <Avatar img={image} userId={isNormalChat ? users[0].id : undefined} />
          <div className="user-meta">
            <p className="username">{nameTemp}</p>
            <p className="last-seen">
              {users.length > 0 && (
                <LastSeen
                  userId={users[0].id}
                  usersCounter={users.length + 1}
                />
              )}
            </p>
          </div>
        </div>
      </div>
      {chatDetailsMenu && (
        <ChatDetailsMenu
          chat={selectedChat}
          close={() => setChatDetailsMenu(false)}
        />
      )}
    </>
  );
}

// clients/sveltekit-client/src/lib/components/chat/ChatHeader/ChatHeader.svelte
<script lang="ts">
	// Styling
	import './ChatHeader.scss';

	// Components
	import Avatar from '../Avatar/Avatar.svelte';
	import ChatDetailsMenu from '../ChatDetailsMenu/ChatDetailsMenu.svelte';
	import LastSeen from '../LastSeen/LastSeen.svelte';

	// Various
	import { browser } from '$app/environment';
	import TokenService from '$lib/services/token.service';
	import { selectedChat } from '$lib/stores/SelectedChatStore';
	import { users } from '$lib/stores/UserStore';
	import type { Chat, ChatParticipant, User } from '$lib/types/prisma';
	import { getUsersMetaByParticipants } from '$lib/services/util.service';

	// States
	let userList: User[] = [];
	let selected: Chat | null = null;
	let image = '';
	let nameTemp = '';
	let isGroupChat = false;
	let isSingleChat = false;
	let isNormalChat = false;
	let chatDetailsMenu = false;
	let chatUsers: User[] = [];

	// Subscribe to stores
	users.subscribe((users) => (userList = users));
	selectedChat.subscribe((chat) => (selected = chat));

	$: if (browser && selected) {
		let self = TokenService.getUser();

		// Get userlist meta data and remove self
		chatUsers = getUsersMetaByParticipants((selected as Chat).ChatParticipant, userList);
		const index = chatUsers.findIndex((u) => u.id === self?.id);
		chatUsers = chatUsers.toSpliced(index, 1);

		// Determine chat type
		isGroupChat = chatUsers.length > 1;
		isSingleChat = chatUsers.length === 0;
		isNormalChat = chatUsers.length === 1;

		// Set variables if groupchat
		if (isGroupChat) {
			image = (selected as Chat).avatar || '';
			nameTemp = (selected as Chat).name as string;
		}

		// Set variables if 1:1 chat
		if (isNormalChat) {
			image = chatUsers[0].avatar as string;
			nameTemp = chatUsers[0].username;
		}

		// Set variables if only one member
		if (isSingleChat) {
			image = self?.avatar || '';
			nameTemp = (selected as Chat).name as string;
		}
	}
</script>

{#if selected !== null}
	<div class="chat-header-container" on:click={() => (chatDetailsMenu = true)}>
		<div class="user-information">
			<Avatar img={image} userId={isNormalChat ? chatUsers[0].id : undefined} />
			<div class="user-meta">
				<p class="username">{nameTemp}</p>
				<p class="last-seen">
					{#if chatUsers.length > 0}
						<LastSeen userId={chatUsers[0].id} usersCounter={chatUsers.length + 1} />
					{/if}
				</p>
			</div>
		</div>
	</div>
	{#if chatDetailsMenu}
		<ChatDetailsMenu chat={selected} close={() => (chatDetailsMenu = false)} />
	{/if}
{/if}
