// clients/react-client/src/components/form/ButtonInput/ButtonInput.tsx
// Styling
import "./ButtonInput.scss";

interface IProps {
  onClick: Function;
  type: "primary" | "secondary";
  label: string;
  loading?: boolean;
}

export default function ButtonInput({
  onClick,
  type,
  label,
  loading = false,
}: IProps) {
  // Only do action, if loading state is false
  const action = () => {
    if (!loading) onClick();
  };

  return (
    <button
      className={`button-input ${type}`}
      onClick={action}
      disabled={loading}
    >
      {loading ? <div className="loading-circle"></div> : label}
    </button>
  );
}

// clients/sveltekit-client/src/lib/components/form/ButtonInput/ButtonInput.svelte
<script lang="ts">
	// Styling
	import './ButtonInput.scss';

	// Props
	export let type: 'primary' | 'secondary' = 'primary';
	export let label: string = '';
	export let loading: boolean = false;
	export let onClick: () => void = () => {};

	function action() {
		if (!loading) onClick();
	}
</script>

<button class="button-input {type}" on:click={action} disabled={loading}>
	{#if loading}
		<div class="loading-circle"></div>
	{:else}
		{label}
		<slot></slot>
	{/if}
</button>
