// clients/sveltekit-client/src/lib/components/chat/Avatar/Avatar.svelte
<script lang="ts">
	import { users } from '$lib/stores/UserStore';
	import type { User } from '$lib/types/prisma';
	import './Avatar.scss';

	export let onlineDot: boolean = false;
	export let img: string | null = null;
	export let loading: boolean = false;
	export let userId: string | null = null;
	let user: User | null = null;
	let showDot = false;

	users.subscribe((userList) => {
		let found = userList.find((u) => u.id === userId);
		if (found) user = found;
	});

	$: {
		if (onlineDot) showDot = true;
		if (user) {
			if ((user as User).online) showDot = true;
		}
	}
</script>

{#if loading}
	<div class="avatar loading"></div>
{:else if img !== null}
	<div class="avatar">
		<img src={'http://localhost:4000/avatar/' + img} alt="" />
		{#if showDot}<div class="online-dot"></div>{/if}
	</div>
{:else}
	<div class="avatar">
		{#if showDot}
			<div class="online-dot"></div>
		{/if}
	</div>
{/if}

// clients/react-client/src/components/chat/Avatar/Avatar.tsx
// Package imports
import { useContext } from "react";

// Custom imports
import { UserOnlineContext } from "../../../context/UserOnlineContext";

// Styling
import "./Avatar.scss";

interface IProps {
  img?: string | null;
  loading?: boolean;
  onlineDot?: boolean;
  userId?: string;
}

export default function Avatar({
  img,
  loading = false,
  onlineDot,
  userId,
}: IProps) {
  const userList = useContext(UserOnlineContext);

  if (loading) return <div className="avatar loading"></div>;

  let showDot = false;
  if (onlineDot || (userId && userList.getUserMeta(userId)?.online)) {
    showDot = true;
  }

  if (img !== null)
    return (
      <div className="avatar">
        <img src={"http://localhost:4000/avatar/" + img} />
        {showDot && <div className="online-dot"></div>}
      </div>
    );

  return (
    <div className="avatar">
      {showDot && <div className="online-dot"></div>}
    </div>
  );
}
