// clients/react-client/src/components/chat/ChatWindow/ChatWindow.tsx
import ChatHeader from "../ChatHeader/ChatHeader";
import ChatHistory from "../ChatHistory/ChatHistory";
import NewMessageBar from "../NewMessageBar/NewMessageBar";
import "./ChatWindow.scss";

export default function ChatWindow() {
  // Hooks
  return (
    <div className="chat-window-container">
      <ChatHeader />
      <ChatHistory />
      <NewMessageBar />
    </div>
  );
}

// clients/sveltekit-client/src/lib/components/chat/ChatWindow/ChatWindow.svelte
<script lang="ts">
	import ChatHeader from '../ChatHeader/ChatHeader.svelte';
	import ChatHistory from '../ChatHistory/ChatHistory.svelte';
	import NewMessageBar from '../NewMessageBar/NewMessageBar.svelte';
	import './ChatWindow.scss';
</script>

<div class="chat-window-container">
	<ChatHeader />
	<ChatHistory />
	<NewMessageBar />
</div>
