// clients/react-client/src/components/form/MessageBox/MessageBox.tsx
// Styling
import "./MessageBox.scss";

interface IProps {
  type: "error" | "success" | "warning";
  message: string;
}

export default function MessageBox({ type, message }: IProps) {
  let title = "Nachricht";
  let className = "success";

  if (type === "error") {
    title = "Fehler";
    className = "error";
  }

  if (type === "warning") {
    title = "Hinweis";
    className = "warning";
  }

  // Return empty box when no message was given
  if (message === "") return <></>;

  return (
    <div className={`message-box-container ${className}`}>
      <p className="title">{title}</p>
      <div className="message">
        <p>{message}</p>
      </div>
    </div>
  );
}

// clients/sveltekit-client/src/lib/components/form/MessageBox/MessageBox.svelte
<script lang="ts">
	import './MessageBox.scss';

	export let type: 'error' | 'success' | 'warning';
	export let message: string;
	let title = 'Nachricht';
	let className = 'success';

	$: {
		if (type === 'error') {
			title = 'Fehler';
			className = 'error';
		}

		if (type === 'warning') {
			title = 'Hinweis';
			className = 'warning';
		}
	}
</script>

{#if message !== ''}
	<div class="message-box-container {className}">
		<p class="title">{title}</p>
		<div class="message">
			<p>{message}</p>
		</div>
	</div>
{/if}
